### ISSUE TITLE
google的android性能优化

### ISSUE THREAD

**Issue by 39074321** [PaicHyperionDev/MobileDevWeekly#115]
2015年伊始，Google发布了关于Android性能优化典范的专题，一共16个短视频，每个3-5分钟，帮助开发者创建更快更优秀的Android App。课程专题不仅仅介绍了Android系统中有关性能问题的底层工作原理，同时也介绍了如何通过工具来找出性能问题以及提升性能的建议。主要从三个方面展开，Android的渲染机制，内存与GC，电量优化。
http://www.techug.com/android-performance-patterns

http://www.techug.com/android-2

**Comment by ASCE1885** [comment]
这个已经收录在前面几期的周报里面啦
