### ISSUE TITLE
[Android] leakcanary：用于检测Android/Java内存泄漏的库

### ISSUE THREAD

**Issue by wzpan** [PaicHyperionDev/MobileDevWeekly#163]
https://github.com/square/leakcanary

**Comment by wzpan** [comment]
中文说明：http://www.liaohuqiu.net/cn/posts/leak-canary-read-me/
使用案例：http://www.liaohuqiu.net/cn/posts/leak-canary/

**Comment by ASCE1885** [comment]
这个以前周报介绍过了

**Comment by wzpan** [comment]
哦哦。那我关了它。
