### ISSUE TITLE
涅槃重生：技术到管理的跨越转型

### ISSUE THREAD

**Issue by zhongyang** [PaicHyperionDev/MobileDevWeekly#172]
很不错的演讲，希望让更多人看到

[http://www.infoq.com/cn/presentations/stride-across-and-transconformation-from-technology-to-the-management](url)

小猿搜题在2015年元旦对外推出，随着公司规模的扩大，也让我有了从一个纯技术的iOS程序员到产品技术负责人的经历。从技术转管理的过程是痛苦的，然而团队管理给产品带来的影响也是巨大的。经过自己和团队的努力，小猿搜题在不到一年的时间内，已经积累了超过4000万的用户。我将在此次话题中，分享我从一个iOS开发转型管理的心得和感悟。

**Comment by ASCE1885** [comment]
这篇文章之前已经收录过了
