### ISSUE TITLE
［Android］Sky：一个基于 Dart 的高性能移动应用 UI 框架

### ISSUE THREAD

**Issue by 39074321** [PaicHyperionDev/MobileDevWeekly#22]
Sky 并不是一种开发语言，而是一个高性能的移动应用 UI 框架，目前还只是一个试验性项目。

GitHub 主页地址：https://github.com/domokit/sky_sdk

中文：http://android.jobbole.com/80930/

**Comment by ASCE1885** [comment]
这个已经收录在第一期周报里面了
