### ISSUE TITLE
程序员如何提高影响力

### ISSUE THREAD

**Issue by 39074321** [PaicHyperionDev/MobileDevWeekly#79]
http://www.ituring.com.cn/article/199043

每个人都可以是一个品牌，对于一个程序员来说，我们的ID就是我们的品牌。而构成品牌的有多个要素:

博客
Github
Weibo(or Twitter)
StackOverflow(or SegmentFault, Zhihu)
等等。

**Comment by ASCE1885** [comment]
重复了
