### ISSUE TITLE
iOS应用架构谈 view层的组织和调用方案

### ISSUE THREAD

**Issue by iamfog** [PaicHyperionDev/MobileDevWeekly#8]
http://casatwy.com/iosying-yong-jia-gou-tan-viewceng-de-zu-zhi-he-diao-yong-fang-an.html

**Comment by ASCE1885** [comment]
这篇文章已经收录在[第一期周报](https://github.com/PaicHyperionDev/MobileDevWeekly/blob/master/%E5%B9%B3%E5%AE%89%E7%A7%91%E6%8A%80%E7%A7%BB%E5%8A%A8%E5%BC%80%E5%8F%91%E4%BA%8C%E9%98%9F%E6%8A%80%E6%9C%AF%E5%91%A8%E6%8A%A5%EF%BC%88%E7%AC%AC%E4%B8%80%E6%9C%9F%EF%BC%89.md)里面了
