### ISSUE TITLE
[开源函数库及工具] Facebook 开源静态代码分析工具 Infer

### ISSUE THREAD

**Issue by wzpan** [PaicHyperionDev/MobileDevWeekly#95]
http://mp.weixin.qq.com/s?__biz=MjM5NzM0MjcyMQ==&mid=205821045&idx=2&sn=6b5b724724f77b1a409b85d1ee70dc5c&scene=2&from=timeline&isappinstalled=0#rd

**Comment by Freedom000** [comment]
工具呢

**Comment by wzpan** [comment]
http://fbinfer.com/

**Comment by Freedom000** [comment]
Good job!
